"""aa

Revision ID: 1b608ff10f57
Revises: fae1bae844e1
Create Date: 2022-12-02 17:10:05.326754

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from env import DB_SCHEMA



# revision identifiers, used by Alembic.
revision = '1b608ff10f57'
down_revision = 'fae1bae844e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('board',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('board_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('writer', sa.String(length=32), nullable=False),
    sa.Column('content', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('board_id'),
    schema=DB_SCHEMA
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('board', schema=DB_SCHEMA)
    # ### end Alembic commands ###
