"""add user

Revision ID: 43674e62be5a
Revises: 
Create Date: 2022-10-26 11:41:18.914834

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from env import DB_SCHEMA



# revision identifiers, used by Alembic.
revision = '43674e62be5a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.Column('password', sqlalchemy_utils.types.password.PasswordType(schemes=[
        'pbkdf2_sha512',
        'md5_crypt'
    ], deprecated=['md5_crypt']), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('tier', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=16), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('username'),
    schema=DB_SCHEMA
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user', schema=DB_SCHEMA)
    # ### end Alembic commands ###
