"""aa

Revision ID: 63f34a3d885c
Revises: 43674e62be5a
Create Date: 2022-12-02 17:04:45.175298

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from env import DB_SCHEMA



# revision identifiers, used by Alembic.
revision = '63f34a3d885c'
down_revision = '43674e62be5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
