"""aa

Revision ID: d9061d68cd4d
Revises: 63f34a3d885c
Create Date: 2022-12-02 17:06:31.599282

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from env import DB_SCHEMA



# revision identifiers, used by Alembic.
revision = 'd9061d68cd4d'
down_revision = '63f34a3d885c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'board', ['board_id'], schema=DB_SCHEMA)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'board', schema=DB_SCHEMA, type_='unique')
    # ### end Alembic commands ###
