"""aa

Revision ID: dc5dd4a497ee
Revises: d9061d68cd4d
Create Date: 2022-12-02 17:07:50.587364

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from env import DB_SCHEMA



# revision identifiers, used by Alembic.
revision = 'dc5dd4a497ee'
down_revision = 'd9061d68cd4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('board_board_id_key', 'board', schema=DB_SCHEMA, type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('board_board_id_key', 'board', ['board_id'], schema=DB_SCHEMA)
    # ### end Alembic commands ###
