"""aa

Revision ID: fae1bae844e1
Revises: dc5dd4a497ee
Create Date: 2022-12-02 17:09:24.261451

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from env import DB_SCHEMA



# revision identifiers, used by Alembic.
revision = 'fae1bae844e1'
down_revision = 'dc5dd4a497ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
